import { Metadata } from "next";
import Product from "./product";

export const metadata: Metadata = {
    title: "Sản phẩm",
    description: "Generated by create next app"
}

const ProductPage = () => {
    return (
        <div>
            <Product />
        </div>
    )
}

export default ProductPage;