import Banner from "./banner/banner";
import Benefit from "./benefit/benefit";
import Nav from "./nav/nav";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Tiệm hoa Cát Tường",
    description: "Generated by create next app",
}

export default function Home() {
  return (
    <>
      <div id="banner">
        <Banner />
      </div>
      <div id="nav">
        <Nav/>
      </div>
      <div id="benefit">
        <Benefit />
      </div>
    </>
  );
}
