import { Metadata } from "next"
import Detail from "./detail"

export const metadata:Metadata = {
    title: "Chi tiết sản phẩm",
    description: "Generated by create next app"
}

const DetailPage = () =>{
    return(
        <div>
            <Detail/>
        </div>
    )
}

export default DetailPage;